python3 attack_classification.py \
        --dataset_path data/imdb  \
        --word_embeddings_path glove.6B.200d.txt \
        --target_model bert \
        --counter_fitting_cos_sim_path mat.txt \
        --target_dataset imdb \
        --target_model_path BERT/results/imdb \
        --counter_fitting_embeddings_path  counter-fitted-vectors.txt \
        --USE_cache_path " " \
        --max_seq_length 256 \
        --sim_score_window 40 \
        --sim_score_threshold 0.8 \
        --top_k_words 60 \
        --fuzz 70 \
        --nclasses 2 &&
python3 attack_classification.py \
        --dataset_path data/yelp  \
        --word_embeddings_path glove.6B.200d.txt \
        --target_model bert \
        --counter_fitting_cos_sim_path mat.txt \
        --target_dataset yelp \
        --target_model_path BERT/results/yelp \
        --counter_fitting_embeddings_path  counter-fitted-vectors.txt \
        --USE_cache_path " " \
        --max_seq_length 256 \
        --sim_score_window 40 \
        --sim_score_threshold 0.8 \
        --top_k_words 60 \
        --fuzz 70 \ &&
python3 attack_classification.py \
        --dataset_path data/mr  \
        --word_embeddings_path glove.6B.200d.txt \
        --target_model bert \
        --counter_fitting_cos_sim_path mat.txt \
        --target_dataset mr \
        --target_model_path BERT/results/mr \
        --counter_fitting_embeddings_path  counter-fitted-vectors.txt \
        --USE_cache_path " " \
        --max_seq_length 256 \
        --sim_score_window 40 \
        --sim_score_threshold 0.8 \
        --top_k_words 60 \
        --fuzz 70 \
        --nclasses 2
